### ISSUE TITLE
Deploy ELIZA chatbot to GitHub Pages

### ISSUE THREAD

**Issue by Cpgeragh** [Cpgeragh/Emerging-Technologies#30]
**Description:**  
Set up GitHub Actions to deploy the ELIZA chatbot folder to GitHub Pages.  

**Tasks:**  
- [x] Create the GitHub Actions workflow.
- [x] Configure the workflow to deploy the contents of the `eliza` folder.  
- [x] Enable GitHub Pages in the repository settings.
- [x] Verify that the chatbot is accessible via the live GitHub Pages link.

**Comment by Cpgeragh** [comment]
This has been completed successfully, this issue can now be closed.
