### ISSUE TITLE
Update README.md with project details

### ISSUE THREAD

**Issue by Cpgeragh** [Cpgeragh/Emerging-Technologies#31]
**Description:**  
Document the ELIZA chatbot project in the repository’s README file.  

**Tasks:**  
- [x] Add an introduction explaining the purpose and functionality of the ELIZA chatbot.  
- [x] Include instructions on how to use the chatbot.  
- [x] Add a direct link to the live GitHub Pages deployment.  
- [x] Update the repository structure section to include the `eliza` folder.  
- [x] Commit changes to the README file.

**Comment by Cpgeragh** [comment]
This has been completed, this issue can now be closed.
